services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args: [PORT]
    ports:
      - "${EXPORTER_PORT:-9090}:${EXPORTER_PORT:-9090}"
    environment:
      - C411_USERNAME=${C411_USERNAME:-}
      - C411_PASSWORD=${C411_PASSWORD:-}
      - METRICS_PATH=${METRICS_PATH:-/metrics}
      - PORT=${PORT:-9090}
      - SCRAPE_INTERVAL=${SCRAPE_INTERVAL:-5m}
      - C411_API_BASE_URL=${C411_API_BASE_URL:-c411.org}
    restart: unless-stopped
